import { Note } from '../../../types/note';

const mockNotesDetail: Note[] = [
  {
    _id: '1',
    title: 'Test Note',
    content: 'Some content',
    subject: 'Math',
    grade: '10',
    semester: '1',
    quarter: '1',
    topic: 'Algebra',
    isPublic: true,
    fileUrl: 'http://example.com/file.pdf',
    fileType: 'pdf',
    viewCount: 10,
    downloadCount: 2,
    averageRating: 4.5,
    rating: 0,
    ratingCount: 2,
    ratings: [],
    flashcards: [],
    user: 'user123',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    aiSummary: '',
    aiSummaryKeyPoints: [],
  },
  {
    _id: '2',
    title: 'Test Note 2',
    content: 'Test content 2',
    subject: 'Test Subject',
    grade: 'Test Grade',
    semester: 'Test Semester',
    quarter: 'Test Quarter',
    topic: 'Test Topic',
    isPublic: true,
    fileUrl: 'http://example.com/test2.pdf',
    fileType: 'application/pdf',
    viewCount: 0,
    downloadCount: 0,
    averageRating: 0,
    rating: 0,
    ratingCount: 0,
    ratings: [],
    flashcards: [],
    user: 'user123',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    aiSummary: '',
    aiSummaryKeyPoints: [],
  }
]; 