import { Note } from '../../../../types/note';

const mockNote = {
  _id: '1',
  title: 'Test Note',
  content: 'Some content',
  subject: 'Math',
  grade: '10',
  semester: '1',
  quarter: '1',
  topic: 'Algebra',
  isPublic: true,
  fileUrl: 'http://example.com/file.pdf',
  fileType: 'pdf',
  viewCount: 10,
  downloadCount: 2,
  averageRating: 4.5,
  ratingCount: 2,
  ratings: [],
  flashcards: [],
  user: 'user123',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  aiSummary: '',
  aiSummaryKeyPoints: [],
  asset_id: '1',
}; 