[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Improve security with standard headers
[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Permissions-Policy = "camera=(), microphone=(), geolocation=()"
      Content-Security-Policy = "default-src 'self'; img-src 'self' data: blob: https://*.cloudinary.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.cloudinary.com https://edu-guardian-backend.onrender.com; frame-src 'self' https://*.cloudinary.com; child-src 'self' https://*.cloudinary.com; media-src 'self' https://*.cloudinary.com; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/*.js"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
      
# Environment variables for production
[context.production.environment]
  # Note: Set these in the Netlify UI, not here for security
  # VITE_API_URL = "https://edu-guardian-backend.onrender.com"
  # VITE_CLOUDINARY_CLOUD_NAME = "dbnk6q2k6"
  # VITE_CLOUDINARY_API_KEY = "384752541685726"
  # VITE_CLOUDINARY_UPLOAD_PRESET = "edu_guardian" 