name: Test & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
    
    - name: Run Backend Tests
      run: |
        cd backend
        npm run test:coverage
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/eduguardian_test
        JWT_SECRET: test_secret
        JWT_EXPIRE: 30d
        JWT_COOKIE_EXPIRE: 30
        SMTP_HOST: smtp.ethereal.email
        SMTP_PORT: 587
        SMTP_EMAIL: test@test.com
        SMTP_PASSWORD: test_password
        FROM_EMAIL: noreply@eduguardian.com
        FROM_NAME: EduGuardian
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm run test:coverage
    
    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Check Coverage Thresholds
      run: |
        cd backend
        npm run test:coverage -- --coverageThreshold='{"global":{"statements":95,"branches":95,"functions":95,"lines":95}}'
        cd ../frontend
        npm run test:coverage -- --coverageThreshold='{"global":{"statements":95,"branches":95,"functions":95,"lines":95}}'

  sonarcloud:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 